module.exports = {
  User: require('./User'),
  Product: require('./Product'),
  Listing: require('./Listing'),
  PriceHistory: require('./PriceHistory'),
  SearchCache: require('./SearchCache'),
  Wishlist: require('./Wishlist'),
  Alert: require('./Alert'),
  Notification: require('./Notification'),
  ScrapeLog: require('./ScrapeLog'),
  Category: require('./Category'),
  Setting: require('./Setting'),
  JobRun: require('./JobRun'),
  PLATFORMS: require('./plugins').PLATFORMS,
};
